### ISSUE TITLE
Tags not matching PyPi releases?

### ISSUE THREAD

**Issue by justinclift** [databendlabs/databend-sqlalchemy#2]
While tracking down an error in an application, came across some potential weirdness with the `databend-sqlalchemy` package.

At present PyPi is showing the latest release to be version 0.2.4.  However, the latest tag in this repo is 0.2.3.

Is that because tags in this repo aren't really kept in sync, or has potentially something bad happened with the PyPi release? :frowning:

**Comment by BohuTANG** [comment]
Sorry for the delay response and thank you for pointing this out. 
To address this issue, I'd like to tag @hantmac

**Comment by hantmac** [comment]
@justinclift Sorry for delay response 😄 . The tag on pypi it the latest release which is version 0.2.4. I just forgot update the repo tag. Thanks for your help!

**Comment by justinclift** [comment]
Cool, thanks for getting it sorted out. :smile:
