### ISSUE TITLE
Trying to pass a regular expression parameter, dollar sign is doubled

### ISSUE THREAD

**Issue by rad-pat** [databendlabs/databend-sqlalchemy#47]
Trying to do similar to:

`sqlalchemy.select(sqlalchemy.func.regexp_like(col, '^[0-9]*$'))`

The dollar sign is doubled in the generated SQL because of this line https://github.com/databendlabs/databend-sqlalchemy/blob/3b65a3005f84127856a18b76d3c754f4ef26d63b/databend_sqlalchemy/connector.py#L41

@hantmac, any idea about the reason for this replacement?

**Comment by hantmac** [comment]
@rad-pat Hi , Replacing a single $ with $$ ensures that $ in the original string is correctly interpreted as a literal character and 
this can also helps prevent SQL injection and syntax errors.

**Comment by rad-pat** [comment]
Thanks, do you perhaps have an example of this so I can set up a test for it? Obviously I want to fix the issue I have without breaking other use cases.

**Comment by rad-pat** [comment]
The best solution by far would be to be able to push the parameters into the driver, but for now the bendSQL doesn't seem to support query parameters for some reason

**Comment by hantmac** [comment]
> Thanks, do you perhaps have an example of this so I can set up a test for it? Obviously I want to fix the issue I have without breaking other use cases.

For example: 
```
price = "$100"
query = "SELECT * FROM products WHERE price_display=%s"
```

# after
```
SELECT * FROM products WHERE price_display='$$100'
```


# orignal
path = "C:\Users\file"
query = "SELECT * FROM files WHERE path=%s"

# after
```
SELECT * FROM files WHERE path='C:\\Users\\file'
```

**Comment by rad-pat** [comment]
@hantmac, I tried these queries with the bendsql, the escaped paths work fine, but the double dollar signs are not substituted..
```
CREATE TABLE IF NOT EXISTS t_str (c1 string);
INSERT INTO t_str VALUES ('$100');
INSERT INTO t_str VALUES ('$$100');
INSERT INTO t_str VALUES ('c:\\some\\path');
INSERT INTO t_str VALUES ('c:\some\path');
select * from t_str;
┌──────────────────┐
│        c1        │
│ Nullable(String) │
├──────────────────┤
│ c:\some\path     │
│ $$100            │
│ $100             │
│ c:\some\path     │
└──────────────────┘
select * from t_str where c1 = '$100';
┌──────────────────┐
│        c1        │
│ Nullable(String) │
├──────────────────┤
│ $100             │
└──────────────────┘
select * from t_str where c1 = '$$100';
┌──────────────────┐
│        c1        │
│ Nullable(String) │
├──────────────────┤
│ $$100            │
└──────────────────┘
```
Possible to just remove the replacement of `$` with `$$` ?

**Comment by hantmac** [comment]
> @hantmac, I tried these queries with the bendsql, the escaped paths work fine, but the double dollar signs are not substituted..
> 
> ```
> CREATE TABLE IF NOT EXISTS t_str (c1 string);
> INSERT INTO t_str VALUES ('$100');
> INSERT INTO t_str VALUES ('$$100');
> INSERT INTO t_str VALUES ('c:\\some\\path');
> INSERT INTO t_str VALUES ('c:\some\path');
> select * from t_str;
> ┌──────────────────┐
> │        c1        │
> │ Nullable(String) │
> ├──────────────────┤
> │ c:\some\path     │
> │ $$100            │
> │ $100             │
> │ c:\some\path     │
> └──────────────────┘
> select * from t_str where c1 = '$100';
> ┌──────────────────┐
> │        c1        │
> │ Nullable(String) │
> ├──────────────────┤
> │ $100             │
> └──────────────────┘
> select * from t_str where c1 = '$$100';
> ┌──────────────────┐
> │        c1        │
> │ Nullable(String) │
> ├──────────────────┤
> │ $$100            │
> └──────────────────┘
> ```
> 
> Possible to just remove the replacement of `$` with `$$` ?

Oh I forgot it. The replacement is suit for `databend-py`, but now the driver has been changed to `bendSQL`, so it should be removed. Thanks!
